# -*- coding: utf-8 -*-
"""Copia de Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KfSz-VqMEkws2s_gIJffd28PRmh5ge4e
"""

# 1. Creación de la lista de estudiantes
Estudiantes=[("Andrea Ramirez",18,4.5), ("Pedro Henao",26,4.8), ("Ana Zabala",29,3.7), ("Juan Rodas", 19,3.8), ("Diego Campos",22,2.2), ("Alejandra Arias",32,4.8), ("Laura Restrepo",21,2.9), ("Juan Rojas",26,4.6)]

# 2. Mostar la información de la lista
print("Punto 2")
for item in Estudiantes:
    print(f"{item[0]} tiene {item[1]} años y obtuvo una nota de {item[2]}")
    print("  ")

# 3. Clasificación de las notas
print("Punto 3")
for item in Estudiantes:
    if item[2] >= 4.5:
        print(f"{item[0]} tiene una calificación Excelente")
        print("  ")
    elif 4.0 <= item[2] < 4.49:
        print(f"{item[0]} tiene una calificación Buena")
        print("  ")
    elif 3.0 <= item[2] < 3.99:
        print(f"{item[0]} tiene una calificación Aceptable")
        print("  ")
    else:
        print(f"{item[0]} Reprobó")
        print("  ")

# 4. Promedio de notas
print("Punto 4")
Suma_notas=0
Cantidad_estudiantes=0
for item in Estudiantes:
    Suma_notas +=item[2]
    Cantidad_estudiantes +=1

Promedio=Suma_notas/Cantidad_estudiantes
print(f"El promedio de notas es de {Promedio:.2f}")

# 5. Búsqueda del estudiante
print("Punto 5")
Nombre=str(input("Ingresa tu nombre: "))
Encontrado=False

for item in Estudiantes:
  if Nombre == item[0]:
    Encontrado=True
    break
if Encontrado == True:
  print(f"{Nombre} te encuentras en la lista")
else:
  print(f"{Nombre} no te encuentras en la lista")

# 6. Diccionario de ciudades
print("Punto 6")
Estudiantes_Ciudades={"Andrea Ramirez": "Bogotá", "Pedro Henao": "Pasto", "Ana Zabala": "Barranquilla", "Juan Rodas": "Bogotá", "Diego Campos": "Cartagena", "Alejandra Arias": "Pasto", "Laura Restrepo": "Pereira", "Juan Rojas": "Pasto"}
for nombre, ciudad in Estudiantes_Ciudades.items():
    print(f"{nombre} vive en {ciudad}")
    print("  ")

# 7. Conteo por ciudad
print("Punto 7")
rep_ciudades={}
for ciudad in Estudiantes_Ciudades.values():
    if ciudad in rep_ciudades:
        rep_ciudades[ciudad] +=1
    else:
        rep_ciudades[ciudad]=1
print(rep_ciudades)

# 8. Ingreso de número
print("Punto 8")
Sum_Numeros=0
Cont_Numeros=0
while True:
  Numero = int(input("Ingresa un número: "))
  if Numero == 0:
    break
  Sum_Numeros +=Numero
  Cont_Numeros +=1
Promedio = Sum_Numeros/Cont_Numeros
print("  ")
print(f"La cantidad de números ingresados son: {Cont_Numeros}")
print(f"La suma total es: {Sum_Numeros}")
print(f"El promedio es: {Promedio:.2f}")

# 9. Break and Continue
print("Punto 9")
for numero in range(1, 30):
    if numero % 3 == 0:
      print(numero)
      continue
    elif numero == 25:
        break
